<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


class CreateSessionTokenFromTemplateRequestBody
{
    /**
     * Use this parameter to override the JWT token lifetime.
     *
     * @var ?float $expiresInSeconds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_in_seconds')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $expiresInSeconds = null;

    /**
     * @param  ?float  $expiresInSeconds
     * @phpstan-pure
     */
    public function __construct(?float $expiresInSeconds = null)
    {
        $this->expiresInSeconds = $expiresInSeconds;
    }
}