<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;

use Clerk\Backend\Utils\SpeakeasyMetadata;
class ListSAMLConnectionsRequest
{
    /**
     * Returns SAML connections that have an associated organization ID to the
     *
     * given organizations.
     * For each organization id, the `+` and `-` can be
     * prepended to the id, which denote whether the
     * respective organization should be included or
     * excluded from the result set.
     * Accepts up to 100 organization ids.
     *
     * @var ?array<string> $organizationId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=organization_id')]
    public ?array $organizationId = null;

    /**
     * Applies a limit to the number of results returned.
     *
     * Can be used for paginating the results together with `offset`.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * Skip the first `offset` results when paginating.
     *
     * Needs to be an integer greater or equal to zero.
     * To be used in conjunction with `limit`.
     *
     * @var ?int $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;

    /**
     * @param  ?int  $limit
     * @param  ?int  $offset
     * @param  ?array<string>  $organizationId
     * @phpstan-pure
     */
    public function __construct(?array $organizationId = null, ?int $limit = 10, ?int $offset = 0)
    {
        $this->organizationId = $organizationId;
        $this->limit = $limit;
        $this->offset = $offset;
    }
}