<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Operations;


/**
 * The slug of the email template to use for the invitation email.
 *
 * If not provided, the "invitation" template will be used.
 */
enum TemplateSlug: string
{
    case Invitation = 'invitation';
    case WaitlistInvitation = 'waitlist_invitation';
}
