<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


/** EmailAddress - Success */
class EmailAddress
{
    /**
     * String representing the object's type. Objects of the same type share the same value.
     *
     *
     *
     * @var EmailAddressObject $object
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('object')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\EmailAddressObject')]
    public EmailAddressObject $object;

    /**
     *
     * @var string $emailAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email_address')]
    public string $emailAddress;

    /**
     *
     * @var bool $reserved
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reserved')]
    public bool $reserved;

    /**
     * $linkedTo
     *
     * @var array<IdentificationLink> $linkedTo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('linked_to')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Clerk\Backend\Models\Components\IdentificationLink>')]
    public array $linkedTo;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Unix timestamp of creation
     *
     *
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var Otp|Admin|FromOAuth|null $verification
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Otp|\Clerk\Backend\Models\Components\Admin|\Clerk\Backend\Models\Components\FromOAuth')]
    public Otp|Admin|FromOAuth|null $verification;

    /**
     * Indicates whether this email address domain matches an active enterprise connection.
     *
     *
     *
     * @var ?bool $matchesSsoConnection
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('matches_sso_connection')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $matchesSsoConnection = null;

    /**
     * @param  EmailAddressObject  $object
     * @param  string  $emailAddress
     * @param  bool  $reserved
     * @param  array<IdentificationLink>  $linkedTo
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?string  $id
     * @param  Otp|Admin|FromOAuth|null  $verification
     * @param  ?bool  $matchesSsoConnection
     */
    public function __construct(EmailAddressObject $object, string $emailAddress, bool $reserved, array $linkedTo, int $createdAt, int $updatedAt, ?string $id = null, Otp|Admin|FromOAuth|null $verification = null, ?bool $matchesSsoConnection = null)
    {
        $this->object = $object;
        $this->emailAddress = $emailAddress;
        $this->reserved = $reserved;
        $this->linkedTo = $linkedTo;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->id = $id;
        $this->verification = $verification;
        $this->matchesSsoConnection = $matchesSsoConnection;
    }
}