<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class FromOAuth
{
    /**
     *
     * @var FromOAuthVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\FromOAuthVerificationStatus')]
    public FromOAuthVerificationStatus $status;

    /**
     *
     * @var string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    public string $strategy;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public ?int $expireAt;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?ErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ErrorClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ErrorClerkError $error = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  FromOAuthVerificationStatus  $status
     * @param  string  $strategy
     * @param  ?int  $expireAt
     * @param  ?int  $attempts
     * @param  ?ErrorClerkError  $error
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(FromOAuthVerificationStatus $status, string $strategy, ?int $expireAt = null, ?int $attempts = null, ?ErrorClerkError $error = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->attempts = $attempts;
        $this->error = $error;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}