<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class FromOAuth
{
    /**
     *
     * @var FromOAuthVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\FromOAuthVerificationStatus')]
    public FromOAuthVerificationStatus $status;

    /**
     *
     * @var string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    public string $strategy;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public ?int $expireAt;

    /**
     *
     * @var ?ErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\ErrorClerkError')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ErrorClerkError $error = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $attempts = null;

    /**
     * @param  FromOAuthVerificationStatus  $status
     * @param  string  $strategy
     * @param  ?int  $expireAt
     * @param  ?ErrorClerkError  $error
     * @param  ?int  $attempts
     */
    public function __construct(FromOAuthVerificationStatus $status, string $strategy, ?int $expireAt = null, ?ErrorClerkError $error = null, ?int $attempts = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->error = $error;
        $this->attempts = $attempts;
    }
}