<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Passkey
{
    /**
     *
     * @var PasskeyVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PasskeyVerificationStatus')]
    public PasskeyVerificationStatus $status;

    /**
     *
     * @var PasskeyVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\PasskeyVerificationStrategy')]
    public PasskeyVerificationStrategy $strategy;

    /**
     *
     * @var ?Nonce $nonce
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nonce')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Nonce|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Nonce $nonce = null;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public ?int $expireAt;

    /**
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  PasskeyVerificationStatus  $status
     * @param  PasskeyVerificationStrategy  $strategy
     * @param  ?Nonce  $nonce
     * @param  ?int  $attempts
     * @param  ?int  $expireAt
     * @param  ?string  $message
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(PasskeyVerificationStatus $status, PasskeyVerificationStrategy $strategy, ?Nonce $nonce = null, ?int $attempts = null, ?int $expireAt = null, ?string $message = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->nonce = $nonce;
        $this->attempts = $attempts;
        $this->expireAt = $expireAt;
        $this->message = $message;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}