<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Saml
{
    /**
     *
     * @var SAMLVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SAMLVerificationStatus')]
    public SAMLVerificationStatus $status;

    /**
     *
     * @var SAMLVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SAMLVerificationStrategy')]
    public SAMLVerificationStrategy $strategy;

    /**
     *
     * @var int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public int $expireAt;

    /**
     *
     * @var ?string $externalVerificationRedirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_verification_redirect_url')]
    public ?string $externalVerificationRedirectUrl;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?SAMLErrorClerkError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\SAMLErrorClerkError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SAMLErrorClerkError $error = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  SAMLVerificationStatus  $status
     * @param  SAMLVerificationStrategy  $strategy
     * @param  int  $expireAt
     * @param  ?string  $externalVerificationRedirectUrl
     * @param  ?int  $attempts
     * @param  ?SAMLErrorClerkError  $error
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(SAMLVerificationStatus $status, SAMLVerificationStrategy $strategy, int $expireAt, ?string $externalVerificationRedirectUrl = null, ?int $attempts = null, ?SAMLErrorClerkError $error = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->expireAt = $expireAt;
        $this->externalVerificationRedirectUrl = $externalVerificationRedirectUrl;
        $this->attempts = $attempts;
        $this->error = $error;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}