<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Clerk\Backend\Models\Components;


class Web3Signature
{
    /**
     *
     * @var Web3SignatureVerificationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Web3SignatureVerificationStatus')]
    public Web3SignatureVerificationStatus $status;

    /**
     *
     * @var Web3SignatureVerificationStrategy $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Clerk\Backend\Models\Components\Web3SignatureVerificationStrategy')]
    public Web3SignatureVerificationStrategy $strategy;

    /**
     *
     * @var ?int $attempts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attempts')]
    public ?int $attempts;

    /**
     *
     * @var ?int $expireAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expire_at')]
    public ?int $expireAt;

    /**
     *
     * @var ?string $nonce
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nonce')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nonce = null;

    /**
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?string $verifiedAtClient
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_at_client')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedAtClient = null;

    /**
     * @param  Web3SignatureVerificationStatus  $status
     * @param  Web3SignatureVerificationStrategy  $strategy
     * @param  ?int  $attempts
     * @param  ?int  $expireAt
     * @param  ?string  $nonce
     * @param  ?string  $message
     * @param  ?string  $verifiedAtClient
     * @phpstan-pure
     */
    public function __construct(Web3SignatureVerificationStatus $status, Web3SignatureVerificationStrategy $strategy, ?int $attempts = null, ?int $expireAt = null, ?string $nonce = null, ?string $message = null, ?string $verifiedAtClient = null)
    {
        $this->status = $status;
        $this->strategy = $strategy;
        $this->attempts = $attempts;
        $this->expireAt = $expireAt;
        $this->nonce = $nonce;
        $this->message = $message;
        $this->verifiedAtClient = $verifiedAtClient;
    }
}